{
  "port"                   : 7000,
  "redis_host"             : "192.168.0.2",
  "redis_port"             : 6379,
  "loglevel"               : "info",
  "hivnetworkcsv"          : "/opt/hivtrace/HIVClustering/bin/hivnetworkcsv",
  "tn93dist"               : "/opt/hivtrace/TN93/tn93",
  "bealign"                : "/opt/hivtrace/env/bin/bealign",
  "bam2msa"                : "/opt/hivtrace/env/bin/bam2msa",
  "python"                 : "/opt/hivtrace/env/bin/python3.2",
  "hxb2_fasta"             : "/opt/hivtrace/example_data/hivtrace/example_files/HXB2.FASTA",
  "hxb2_linked_lanl"       : "/opt/hivtrace/example_data/hivtrace/example_files/LANL.HXB2.csv",
  "lanl_fasta"             : "/opt/hivtrace/example_data/hivtrace/example_files/LANL.FASTA",
  "lanl_lewis"             : "/opt/hivtrace/example_data/hivtrace/example_files/LANL_STRIPPED_LEWIS.FASTA",
  "lanl_wheeler"           : "/opt/hivtrace/example_data/hivtrace/example_files/LANL_STRIPPED_WHEELER.FASTA",
  "lanl_tn93output_csv"    : "/opt/hivtrace/example_data/hivtrace/example_files/LANL.TN93OUTPUT.csv",
  "reference"              : "hxb2_prrt",
  "score_matrix"           : "HIV_BETWEEN_F",
  "score_matrix"           : "HIV_BETWEEN_F",
  "output_format"          : "csv",
  "sequence_id_format"     : "plain",
  "ambiguity_handling"     : "average",
  "default_delimiter"      : "|",
  "flea_python"            : "/opt/talign/env/bin/python",
  "flea_pipeline"          : "/opt/flea-pipeline/env_pipeline.py",
  "flea_config"            : "/opt/flea-pipeline/env_pipeline.config",
  "qsub_queue"             : "datamonkey"
}
