{
  "port"                   : 7000,
  "redis_host"             : "192.168.0.2",
  "redis_port"             : 6379,
  "output_dir"             : "/home/sergei/datamonkey-server/app/hivtrace/output/",
  "hivnetworkcsv"          : "/opt/hivtrace/HIVClustering/bin/hivnetworkcsv",
  "tn93dist"               : "/opt/hivtrace/TN93/tn93",
  "bealign"                : "/opt/hivtrace/env/bin/bealign",
  "bam2msa"                : "/opt/hivtrace/env/bin/bam2msa",
  "qsub_script"            : "/home/sergei/datamonkey-server/app/hivtrace/hivtrace_submit.sh",
  "hivtrace"               : "/home/sergei/datamonkey-server/app/hivtrace/hivtrace.py",
  "python"                 : "/opt/hivtrace/env/bin/python3.2",
  "hxb2_fasta"             : "/opt/hivtrace/example_data/hivtrace/example_files/HXB2.FASTA",
  "reference"              : "hxb2_prrt",
  "score_matrix"           : "HIV_BETWEEN_F",
  "output_format"          : "csv",
  "sequence_id_format"     : "plain",
  "ambiguity_handling"     : "average",
  "test_output_dir"        : "/home/sergei/datamonkey-server/hivtrace/tests/res/",
  "default_delimiter"      : "|",
  "script_basepath"        : "/home/sergei/datamonkey-server/analyses/",
  "prime_output_dir"       : "/home/sergei/datamonkey-server/analyses/prime/spool/",
  "lanl_fasta"             : "/home/sergei/datamonkey-server/app/hivtrace/res/LANL.FASTA",
  "lanl_tn93output_csv"    : "/home/sergei/datamonkey-server/app/hivtrace/res/LANL.TN93OUTPUT.csv"
}
