# shellcheck shell=bash
#
# app/cluster-env.sh -- the ONE place the cluster execution environment is
# defined for the analysis wrappers (app/<analysis>/*.sh). SOURCED, never
# executed (tracked mode 0644).
#
# The defaults below are silverback's (OpenHPC, aarch64, OpenMPI 5.0.7 + UCX
# 1.18.0). To run on a different cluster, do NOT edit this file or any wrapper:
#   cp app/cluster-env.local.example app/cluster-env.local.sh   # gitignored
# and set only the DM_ENV_* variables that differ. The site file is sourced
# after the defaults are assigned and before anything is applied.
# DM_ENV_* values from the inherited environment are ignored (with a WARNING),
# because sbatch --export=ALL forwards the whole server environment into every
# job. The inherited LD_LIBRARY_PATH is NOT ignored: it is kept between the
# MPI lib dirs and DM_ENV_LD_APPEND, and --export=ALL forwards the server's,
# so it can hide a wrong DM_ENV_MPI_LIB_DIRS (see "Contract" below).
#
# Why this file exists: the block below used to be copy-pasted into every
# wrapper. The copies drifted -- fubar.sh and bstill.sh kept a dead
# openmpi/gnu/3.1.6 load for years, and every FUBAR job failed in production
# with "libmpi.so.40: cannot open shared object file" until #504. Never
# re-inline module loads or library paths into a wrapper;
# test/cluster-env.test.js fails if you do.
#
# Usage, only via the canonical locator block in each wrapper:
#   . "$DM_APP_DIR/cluster-env.sh" mpi    # HyPhy wrappers: PATH, modules, LD pin, MPI_LIB_PATH
#   . "$DM_APP_DIR/cluster-env.sh" base   # no MPI libraries needed (hivtrace): PATH, modules
# Wrappers find this file through the cwd= parameter and never through $0 or
# BASH_SOURCE. sbatch and Torque qsub run a spooled copy of the batch script
# (e.g. /var/spool/slurmd/job<ID>/slurm_script), so $0 does not point into the
# repo. Inside THIS file BASH_SOURCE[0] is the real path it was sourced from,
# so the site file is found next to it.
#
# Contract:
#   * Sourced BEFORE the wrapper's `trap ... ERR`; wrappers do not use set -e.
#   * Returns 0. The only exit is a bad profile argument, which is a
#     programming error and fails loudly ("Error:" on stderr, "Error" in the
#     status file).
#   * Uses no external command at source time, apart from the optional lmod
#     `module` function. This keeps it working in hivtrace's local mode, where
#     the environment is replaced and PATH is empty.
#   * A site file must not call `exit`, and must return 0: a non-zero return
#     (syntax error, or a failing last command) fails the job loudly, like a
#     bad profile. End it with `true` if its last line is a conditional.
#   * The authoritative signal for a wrong DM_ENV_MPI_LIB_DIRS is the
#     "WARNING: cluster-env: libmpi.so.40 not found in DM_ENV_MPI_LIB_DIRS"
#     line in the job .out. A wrong value may still RUN if the server's
#     inherited LD_LIBRARY_PATH happens to contain MPI libs; validate a new
#     override by submitting once with `env -u LD_LIBRARY_PATH sbatch ...`.
#   * If a site sets DM_ENV_MPI_LIB_DIRS="", the srun task sees
#     LD_LIBRARY_PATH=":$LD_LIBRARY_PATH" (from the wrappers' srun idiom). The
#     empty entry means the current directory; harmless in practice.

DM_ENV_PROFILE="${1:-}"
case "$DM_ENV_PROFILE" in
  mpi|base) ;;
  *)
    echo "Error: cluster-env: profile must be 'mpi' or 'base' (got '$DM_ENV_PROFILE'); source as: . cluster-env.sh mpi" >&2
    _dm_sf="${sfn:-${fn:+${fn}_status}}"
    if [ -n "$_dm_sf" ]; then echo "Error" > "$_dm_sf"; fi
    exit 1
    ;;
esac

# DM_ENV_* inherited from the server environment (pm2 env, service unit) would
# be silently overwritten by the defaults below; say so, and drop them so the
# site-file typo guard does not misattribute them.
for _dm_v in $(compgen -v DM_ENV_); do
  case "$_dm_v" in
    DM_ENV_PROFILE) ;;
    *)
      echo "WARNING: cluster-env: ignoring inherited $_dm_v from the server environment; set it in app/cluster-env.local.sh"
      unset "$_dm_v"
      ;;
  esac
done

# ------------------------------------------------------------------------
# Defaults (silverback). Override ONLY in app/cluster-env.local.sh.
# ------------------------------------------------------------------------
# Prepended to PATH, before module loads (system hyphy and node live here).
DM_ENV_PATH_PREPEND="/usr/local/bin"
# lmod init script. Modules are loaded only when this FILE exists. Silverback
# compute nodes have no lmod, so there the loads are skipped and the
# LD_LIBRARY_PATH pin below is what does the work. We intentionally do not
# fall back to a `module` function inherited through --export=ALL.
DM_ENV_LMOD_INIT="/etc/profile.d/lmod.sh"
# Loaded in order; loading stops at the first failure. Empty = load nothing.
DM_ENV_MODULES="gnu14/14.2.0 openmpi5/5.0.7"
# OpenMPI/UCX library dirs that HYPHYMPI needs at load time. They are NOT on
# the system loader path (there is no ld.so.conf.d entry). Without them the
# binary exits 127 with "libmpi.so.40: cannot open shared object file" before
# it parses any arguments. Used only by profile mpi.
DM_ENV_MPI_LIB_DIRS="/opt/ohpc/pub/mpi/openmpi5-gnu14/5.0.7/lib:/opt/ohpc/pub/mpi/ucx-ohpc/1.18.0/lib"
# Appended after the inherited LD_LIBRARY_PATH (profile mpi). Empty = append nothing.
DM_ENV_LD_APPEND="/usr/lib64"
# Diagnostic only: libraries expected somewhere in DM_ENV_MPI_LIB_DIRS.
DM_ENV_REQUIRED_LIBS="libmpi.so.40 libucp.so.0"

# ------------------------------------------------------------------------
# Site-local override
# ------------------------------------------------------------------------
_dm_self="${BASH_SOURCE[0]}"
case "$_dm_self" in
  */*) _dm_dir="${_dm_self%/*}" ;;
  *)   _dm_dir="." ;;
esac
echo "cluster-env: loaded $_dm_self (profile $DM_ENV_PROFILE)"

if [ -f "$_dm_dir/cluster-env.local.sh" ]; then
  echo "cluster-env: applying site overrides from $_dm_dir/cluster-env.local.sh"
  # Site-local and gitignored, so it cannot be followed statically.
  # shellcheck source=/dev/null
  if ! . "$_dm_dir/cluster-env.local.sh"; then
    # Fatal: continuing would run with partial or silverback settings and fail
    # later at srun with a misleading libmpi error.
    echo "Error: cluster-env: $_dm_dir/cluster-env.local.sh failed (returned non-zero); check with: bash -n $_dm_dir/cluster-env.local.sh (end it with 'true' if its last line is a conditional)" >&2
    _dm_sf="${sfn:-${fn:+${fn}_status}}"
    if [ -n "$_dm_sf" ]; then echo "Error" > "$_dm_sf"; fi
    exit 1
  fi
  # Report typos such as DM_ENV_MODULE instead of silently ignoring them.
  for _dm_v in $(compgen -v DM_ENV_); do
    case "$_dm_v" in
      DM_ENV_PROFILE|DM_ENV_PATH_PREPEND|DM_ENV_LMOD_INIT|DM_ENV_MODULES|DM_ENV_MPI_LIB_DIRS|DM_ENV_LD_APPEND|DM_ENV_REQUIRED_LIBS) ;;
      *) echo "WARNING: cluster-env: unknown setting $_dm_v (typo in cluster-env.local.sh?)" ;;
    esac
  done
fi

# ------------------------------------------------------------------------
# 1. PATH (same effect as the old per-wrapper `export PATH=/usr/local/bin:$PATH`)
# ------------------------------------------------------------------------
if [ -n "$DM_ENV_PATH_PREPEND" ]; then
  export PATH="$DM_ENV_PATH_PREPEND:$PATH"
fi

# ------------------------------------------------------------------------
# 2. Modules: best effort
# ------------------------------------------------------------------------
if [ -n "$DM_ENV_MODULES" ] && [ -n "$DM_ENV_LMOD_INIT" ] && [ -f "$DM_ENV_LMOD_INIT" ]; then
  # System lmod init script, path configurable per site.
  # shellcheck source=/dev/null
  . "$DM_ENV_LMOD_INIT"
  for _dm_m in $DM_ENV_MODULES; do
    if ! module load "$_dm_m" 2>/dev/null; then
      echo "Failed to load module $_dm_m (remaining modules skipped): $DM_ENV_MODULES"
      break
    fi
  done
  module list 2>&1
  echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
elif [ -n "$DM_ENV_MODULES" ]; then
  echo "Module system not available, using system environment"
fi

# ------------------------------------------------------------------------
# 3. MPI/UCX library pin (profile mpi only)
# ------------------------------------------------------------------------
if [ "$DM_ENV_PROFILE" = "mpi" ]; then
  # Used by every srun line in the wrappers:
  #   srun --mpi=$MPI_TYPE -n N /usr/bin/env LD_LIBRARY_PATH="$MPI_LIB_PATH:$LD_LIBRARY_PATH" $HYPHY ...
  # srun propagates the exported value on silverback (verified), but the
  # explicit pin keeps working where srun --export / SLURM_EXPORT_ENV differ.
  MPI_LIB_PATH="$DM_ENV_MPI_LIB_DIRS"

  # With the defaults this is byte-identical to the legacy per-wrapper line
  #   export LD_LIBRARY_PATH=<openmpi5 lib>:<ucx lib>:$LD_LIBRARY_PATH:/usr/lib64
  # including the "::" when nothing was inherited.
  export LD_LIBRARY_PATH="${MPI_LIB_PATH:+$MPI_LIB_PATH:}${LD_LIBRARY_PATH}${DM_ENV_LD_APPEND:+:$DM_ENV_LD_APPEND}"
  echo "LD_LIBRARY_PATH after adjustment: $LD_LIBRARY_PATH"

  # Diagnostic library check (plain bash tests, never fatal).
  if [ -n "$MPI_LIB_PATH" ]; then
    for _dm_l in $DM_ENV_REQUIRED_LIBS; do
      _dm_hit=""
      _dm_ifs="$IFS"; IFS=":"
      for _dm_d in $MPI_LIB_PATH; do
        if [ -n "$_dm_d" ] && [ -e "$_dm_d/$_dm_l" ]; then _dm_hit="$_dm_d/$_dm_l"; break; fi
      done
      IFS="$_dm_ifs"
      if [ -n "$_dm_hit" ]; then
        echo "cluster-env: found $_dm_l at $_dm_hit"
      else
        echo "WARNING: cluster-env: $_dm_l not found in DM_ENV_MPI_LIB_DIRS ($MPI_LIB_PATH); MPI HyPhy runs will fail to load. Set DM_ENV_MPI_LIB_DIRS in app/cluster-env.local.sh"
      fi
    done
  fi
fi

unset _dm_sf _dm_self _dm_dir _dm_v _dm_m _dm_l _dm_hit _dm_ifs _dm_d
return 0
